# Site settings
title: Minga
subtitle: Lorem ipsum dolor sit
email: contacŧ@minga-docu.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
exclude:
  - Gemfile
  - Gemfile.lock
  - dploy.yaml
  - dploy.yml
  - php/
  - resize.sh
  - CNAME
  - resize/
  - node_modules/
  - src/
  - .yo-rc.json
  - package.json
  - package-lock.json
  - webpack.config.js
  - webpack.prod.js